/**
 * List of countries with their emoji flags and currency details
 */
export const countries = [
    { name: "Afghanistan", code: "AF", emoji: "🇦🇫", currency: "Afghan afghani", currency_code: "AFN" },
    { name: "Albania", code: "AL", emoji: "🇦🇱", currency: "Albanian lek", currency_code: "ALL" },
    { name: "Algeria", code: "DZ", emoji: "🇩🇿", currency: "Algerian dinar", currency_code: "DZD" },
    { name: "Andorra", code: "AD", emoji: "🇦🇩", currency: "Euro", currency_code: "EUR" },
    { name: "Angola", code: "AO", emoji: "🇦🇴", currency: "Angolan kwanza", currency_code: "AOA" },
    { name: "Argentina", code: "AR", emoji: "🇦🇷", currency: "Argentine peso", currency_code: "ARS" },
    { name: "Armenia", code: "AM", emoji: "🇦🇲", currency: "Armenian dram", currency_code: "AMD" },
    { name: "Australia", code: "AU", emoji: "🇦🇺", currency: "Australian dollar", currency_code: "AUD" },
    { name: "Austria", code: "AT", emoji: "🇦🇹", currency: "Euro", currency_code: "EUR" },
    { name: "Azerbaijan", code: "AZ", emoji: "🇦🇿", currency: "Azerbaijani manat", currency_code: "AZN" },
    { name: "Bahamas", code: "BS", emoji: "🇧🇸", currency: "Bahamian dollar", currency_code: "BSD" },
    { name: "Bahrain", code: "BH", emoji: "🇧🇭", currency: "Bahraini dinar", currency_code: "BHD" },
    { name: "Bangladesh", code: "BD", emoji: "🇧🇩", currency: "Bangladeshi taka", currency_code: "BDT" },
    { name: "Barbados", code: "BB", emoji: "🇧🇧", currency: "Barbadian dollar", currency_code: "BBD" },
    { name: "Belarus", code: "BY", emoji: "🇧🇾", currency: "Belarusian ruble", currency_code: "BYN" },
    { name: "Belgium", code: "BE", emoji: "🇧🇪", currency: "Euro", currency_code: "EUR" },
    { name: "Belize", code: "BZ", emoji: "🇧🇿", currency: "Belize dollar", currency_code: "BZD" },
    { name: "Benin", code: "BJ", emoji: "🇧🇯", currency: "West African CFA franc", currency_code: "XOF" },
    { name: "Bhutan", code: "BT", emoji: "🇧🇹", currency: "Bhutanese ngultrum", currency_code: "BTN" },
    { name: "Bolivia", code: "BO", emoji: "🇧🇴", currency: "Bolivian boliviano", currency_code: "BOB" },
    { name: "Bosnia and Herzegovina", code: "BA", emoji: "🇧🇦", currency: "Bosnia and Herzegovina convertible mark", currency_code: "BAM" },
    { name: "Botswana", code: "BW", emoji: "🇧🇼", currency: "Botswana pula", currency_code: "BWP" },
    { name: "Brazil", code: "BR", emoji: "🇧🇷", currency: "Brazilian real", currency_code: "BRL" },
    { name: "Brunei", code: "BN", emoji: "🇧🇳", currency: "Brunei dollar", currency_code: "BND" },
    { name: "Bulgaria", code: "BG", emoji: "🇧🇬", currency: "Bulgarian lev", currency_code: "BGN" },
    { name: "Burkina Faso", code: "BF", emoji: "🇧🇫", currency: "West African CFA franc", currency_code: "XOF" },
    { name: "Burundi", code: "BI", emoji: "🇧🇮", currency: "Burundian franc", currency_code: "BIF" },
    { name: "Cambodia", code: "KH", emoji: "🇰🇭", currency: "Cambodian riel", currency_code: "KHR" },
    { name: "Cameroon", code: "CM", emoji: "🇨🇲", currency: "Central African CFA franc", currency_code: "XAF" },
    { name: "Canada", code: "CA", emoji: "🇨🇦", currency: "Canadian dollar", currency_code: "CAD" },
    { name: "Cape Verde", code: "CV", emoji: "🇨🇻", currency: "Cape Verdean escudo", currency_code: "CVE" },
    { name: "Central African Republic", code: "CF", emoji: "🇨🇫", currency: "Central African CFA franc", currency_code: "XAF" },
    { name: "Chad", code: "TD", emoji: "🇹🇩", currency: "Central African CFA franc", currency_code: "XAF" },
    { name: "Chile", code: "CL", emoji: "🇨🇱", currency: "Chilean peso", currency_code: "CLP" },
    { name: "China", code: "CN", emoji: "🇨🇳", currency: "Renminbi", currency_code: "CNY" },
    { name: "Colombia", code: "CO", emoji: "🇨🇴", currency: "Colombian peso", currency_code: "COP" },
    { name: "Comoros", code: "KM", emoji: "🇰🇲", currency: "Comorian franc", currency_code: "KMF" },
    { name: "Congo", code: "CG", emoji: "🇨🇬", currency: "Central African CFA franc", currency_code: "XAF" },
    { name: "Costa Rica", code: "CR", emoji: "🇨🇷", currency: "Costa Rican colón", currency_code: "CRC" },
    { name: "Croatia", code: "HR", emoji: "🇭🇷", currency: "Euro", currency_code: "EUR" },
    { name: "Cuba", code: "CU", emoji: "🇨🇺", currency: "Cuban peso", currency_code: "CUP" },
    { name: "Cyprus", code: "CY", emoji: "🇨🇾", currency: "Euro", currency_code: "EUR" },
    { name: "Czech Republic", code: "CZ", emoji: "🇨🇿", currency: "Czech koruna", currency_code: "CZK" },
    { name: "Denmark", code: "DK", emoji: "🇩🇰", currency: "Danish krone", currency_code: "DKK" },
    { name: "Djibouti", code: "DJ", emoji: "🇩🇯", currency: "Djiboutian franc", currency_code: "DJF" },
    { name: "Dominica", code: "DM", emoji: "🇩🇲", currency: "East Caribbean dollar", currency_code: "XCD" },
    { name: "Dominican Republic", code: "DO", emoji: "🇩🇴", currency: "Dominican peso", currency_code: "DOP" },
    { name: "Ecuador", code: "EC", emoji: "🇪🇨", currency: "United States dollar", currency_code: "USD" },
    { name: "Egypt", code: "EG", emoji: "🇪🇬", currency: "Egyptian pound", currency_code: "EGP" },
    { name: "El Salvador", code: "SV", emoji: "🇸🇻", currency: "United States dollar", currency_code: "USD" },
    { name: "Equatorial Guinea", code: "GQ", emoji: "🇬🇶", currency: "Central African CFA franc", currency_code: "XAF" },
    { name: "Eritrea", code: "ER", emoji: "🇪🇷", currency: "Eritrean nakfa", currency_code: "ERN" },
    { name: "Estonia", code: "EE", emoji: "🇪🇪", currency: "Euro", currency_code: "EUR" },
    { name: "Ethiopia", code: "ET", emoji: "🇪🇹", currency: "Ethiopian birr", currency_code: "ETB" },
    { name: "Fiji", code: "FJ", emoji: "🇫🇯", currency: "Fijian dollar", currency_code: "FJD" },
    { name: "Finland", code: "FI", emoji: "🇫🇮", currency: "Euro", currency_code: "EUR" },
    { name: "France", code: "FR", emoji: "🇫🇷", currency: "Euro", currency_code: "EUR" },
    { name: "Gabon", code: "GA", emoji: "🇬🇦", currency: "Central African CFA franc", currency_code: "XAF" },
    { name: "Gambia", code: "GM", emoji: "🇬🇲", currency: "Gambian dalasi", currency_code: "GMD" },
    { name: "Georgia", code: "GE", emoji: "🇬🇪", currency: "Georgian lari", currency_code: "GEL" },
    { name: "Germany", code: "DE", emoji: "🇩🇪", currency: "Euro", currency_code: "EUR" },
    { name: "Ghana", code: "GH", emoji: "🇬🇭", currency: "Ghanaian cedi", currency_code: "GHS" },
    { name: "Greece", code: "GR", emoji: "🇬🇷", currency: "Euro", currency_code: "EUR" },
    { name: "Grenada", code: "GD", emoji: "🇬🇩", currency: "East Caribbean dollar", currency_code: "XCD" },
    { name: "Guatemala", code: "GT", emoji: "🇬🇹", currency: "Guatemalan quetzal", currency_code: "GTQ" },
    { name: "Guinea", code: "GN", emoji: "🇬🇳", currency: "Guinean franc", currency_code: "GNF" },
    { name: "Guinea-Bissau", code: "GW", emoji: "🇬🇼", currency: "West African CFA franc", currency_code: "XOF" },
    { name: "Guyana", code: "GY", emoji: "🇬🇾", currency: "Guyanese dollar", currency_code: "GYD" },
    { name: "Haiti", code: "HT", emoji: "🇭🇹", currency: "Haitian gourde", currency_code: "HTG" },
    { name: "Honduras", code: "HN", emoji: "🇭🇳", currency: "Honduran lempira", currency_code: "HNL" },
    { name: "Hong Kong", code: "HK", emoji: "🇭🇰", currency: "Hong Kong dollar", currency_code: "HKD" },
    { name: "Hungary", code: "HU", emoji: "🇭🇺", currency: "Hungarian forint", currency_code: "HUF" },
    { name: "Iceland", code: "IS", emoji: "🇮🇸", currency: "Icelandic króna", currency_code: "ISK" },
    { name: "India", code: "IN", emoji: "🇮🇳", currency: "Indian rupee", currency_code: "INR" },
    { name: "Indonesia", code: "ID", emoji: "🇮🇩", currency: "Indonesian rupiah", currency_code: "IDR" },
    { name: "Iran", code: "IR", emoji: "🇮🇷", currency: "Iranian rial", currency_code: "IRR" },
    { name: "Iraq", code: "IQ", emoji: "🇮🇶", currency: "Iraqi dinar", currency_code: "IQD" },
    { name: "Ireland", code: "IE", emoji: "🇮🇪", currency: "Euro", currency_code: "EUR" },
    { name: "Israel", code: "IL", emoji: "🇮🇱", currency: "Israeli new shekel", currency_code: "ILS" },
    { name: "Italy", code: "IT", emoji: "🇮🇹", currency: "Euro", currency_code: "EUR" },
    { name: "Jamaica", code: "JM", emoji: "🇯🇲", currency: "Jamaican dollar", currency_code: "JMD" },
    { name: "Japan", code: "JP", emoji: "🇯🇵", currency: "Japanese yen", currency_code: "JPY" },
    { name: "Jordan", code: "JO", emoji: "🇯🇴", currency: "Jordanian dinar", currency_code: "JOD" },
    { name: "Kazakhstan", code: "KZ", emoji: "🇰🇿", currency: "Kazakhstani tenge", currency_code: "KZT" },
    { name: "Kenya", code: "KE", emoji: "🇰🇪", currency: "Kenyan shilling", currency_code: "KES" },
    { name: "Kiribati", code: "KI", emoji: "🇰🇮", currency: "Australian dollar", currency_code: "AUD" },
    { name: "Kuwait", code: "KW", emoji: "🇰🇼", currency: "Kuwaiti dinar", currency_code: "KWD" },
    { name: "Kyrgyzstan", code: "KG", emoji: "🇰🇬", currency: "Kyrgyzstani som", currency_code: "KGS" },
    { name: "Laos", code: "LA", emoji: "🇱🇦", currency: "Lao kip", currency_code: "LAK" },
    { name: "Latvia", code: "LV", emoji: "🇱🇻", currency: "Euro", currency_code: "EUR" },
    { name: "Lebanon", code: "LB", emoji: "🇱🇧", currency: "Lebanese pound", currency_code: "LBP" },
    { name: "Lesotho", code: "LS", emoji: "🇱🇸", currency: "Lesotho loti", currency_code: "LSL" },
    { name: "Liberia", code: "LR", emoji: "🇱🇷", currency: "Liberian dollar", currency_code: "LRD" },
    { name: "Libya", code: "LY", emoji: "🇱🇾", currency: "Libyan dinar", currency_code: "LYD" },
    { name: "Liechtenstein", code: "LI", emoji: "🇱🇮", currency: "Swiss franc", currency_code: "CHF" },
    { name: "Lithuania", code: "LT", emoji: "🇱🇹", currency: "Euro", currency_code: "EUR" },
    { name: "Luxembourg", code: "LU", emoji: "🇱🇺", currency: "Euro", currency_code: "EUR" },
    { name: "Macedonia", code: "MK", emoji: "🇲🇰", currency: "Macedonian denar", currency_code: "MKD" },
    { name: "Madagascar", code: "MG", emoji: "🇲🇬", currency: "Malagasy ariary", currency_code: "MGA" },
    { name: "Malawi", code: "MW", emoji: "🇲🇼", currency: "Malawian kwacha", currency_code: "MWK" },
    { name: "Malaysia", code: "MY", emoji: "🇲🇾", currency: "Malaysian ringgit", currency_code: "MYR" },
    { name: "Maldives", code: "MV", emoji: "🇲🇻", currency: "Maldivian rufiyaa", currency_code: "MVR" },
    { name: "Mali", code: "ML", emoji: "🇲🇱", currency: "West African CFA franc", currency_code: "XOF" },
    { name: "Malta", code: "MT", emoji: "🇲🇹", currency: "Euro", currency_code: "EUR" },
    { name: "Marshall Islands", code: "MH", emoji: "🇲🇭", currency: "United States dollar", currency_code: "USD" },
    { name: "Mauritania", code: "MR", emoji: "🇲🇷", currency: "Mauritanian ouguiya", currency_code: "MRU" },
    { name: "Mauritius", code: "MU", emoji: "🇲🇺", currency: "Mauritian rupee", currency_code: "MUR" },
    { name: "Mexico", code: "MX", emoji: "🇲🇽", currency: "Mexican peso", currency_code: "MXN" },
    { name: "Micronesia", code: "FM", emoji: "🇫🇲", currency: "United States dollar", currency_code: "USD" },
    { name: "Moldova", code: "MD", emoji: "🇲🇩", currency: "Moldovan leu", currency_code: "MDL" },
    { name: "Monaco", code: "MC", emoji: "🇲🇨", currency: "Euro", currency_code: "EUR" },
    { name: "Mongolia", code: "MN", emoji: "🇲🇳", currency: "Mongolian tögrög", currency_code: "MNT" },
    { name: "Montenegro", code: "ME", emoji: "🇲🇪", currency: "Euro", currency_code: "EUR" },
    { name: "Morocco", code: "MA", emoji: "🇲🇦", currency: "Moroccan dirham", currency_code: "MAD" },
    { name: "Mozambique", code: "MZ", emoji: "🇲🇿", currency: "Mozambican metical", currency_code: "MZN" },
    { name: "Myanmar", code: "MM", emoji: "🇲🇲", currency: "Burmese kyat", currency_code: "MMK" },
    { name: "Namibia", code: "NA", emoji: "🇳🇦", currency: "Namibian dollar", currency_code: "NAD" },
    { name: "Nauru", code: "NR", emoji: "🇳🇷", currency: "Australian dollar", currency_code: "AUD" },
    { name: "Nepal", code: "NP", emoji: "🇳🇵", currency: "Nepalese rupee", currency_code: "NPR" },
    { name: "Netherlands", code: "NL", emoji: "🇳🇱", currency: "Euro", currency_code: "EUR" },
    { name: "New Zealand", code: "NZ", emoji: "🇳🇿", currency: "New Zealand dollar", currency_code: "NZD" },
    { name: "Nicaragua", code: "NI", emoji: "🇳🇮", currency: "Nicaraguan córdoba", currency_code: "NIO" },
    { name: "Niger", code: "NE", emoji: "🇳🇪", currency: "West African CFA franc", currency_code: "XOF" },
    { name: "Nigeria", code: "NG", emoji: "🇳🇬", currency: "Nigerian naira", currency_code: "NGN" },
    { name: "North Korea", code: "KP", emoji: "🇰🇵", currency: "North Korean won", currency_code: "KPW" },
    { name: "Norway", code: "NO", emoji: "🇳🇴", currency: "Norwegian krone", currency_code: "NOK" },
    { name: "Oman", code: "OM", emoji: "🇴🇲", currency: "Omani rial", currency_code: "OMR" },
    { name: "Pakistan", code: "PK", emoji: "🇵🇰", currency: "Pakistani rupee", currency_code: "PKR" },
    { name: "Palau", code: "PW", emoji: "🇵🇼", currency: "United States dollar", currency_code: "USD" },
    { name: "Panama", code: "PA", emoji: "🇵🇦", currency: "Panamanian balboa", currency_code: "PAB" },
    { name: "Papua New Guinea", code: "PG", emoji: "🇵🇬", currency: "Papua New Guinean kina", currency_code: "PGK" },
    { name: "Paraguay", code: "PY", emoji: "🇵🇾", currency: "Paraguayan guaraní", currency_code: "PYG" },
    { name: "Peru", code: "PE", emoji: "🇵🇪", currency: "Peruvian sol", currency_code: "PEN" },
    { name: "Philippines", code: "PH", emoji: "🇵🇭", currency: "Philippine peso", currency_code: "PHP" },
    { name: "Poland", code: "PL", emoji: "🇵🇱", currency: "Polish złoty", currency_code: "PLN" },
    { name: "Portugal", code: "PT", emoji: "🇵🇹", currency: "Euro", currency_code: "EUR" },
    { name: "Qatar", code: "QA", emoji: "🇶🇦", currency: "Qatari riyal", currency_code: "QAR" },
    { name: "Romania", code: "RO", emoji: "🇷🇴", currency: "Romanian leu", currency_code: "RON" },
    { name: "Russia", code: "RU", emoji: "🇷🇺", currency: "Russian ruble", currency_code: "RUB" },
    { name: "Rwanda", code: "RW", emoji: "🇷🇼", currency: "Rwandan franc", currency_code: "RWF" },
    { name: "Saint Kitts and Nevis", code: "KN", emoji: "🇰🇳", currency: "East Caribbean dollar", currency_code: "XCD" },
    { name: "Saint Lucia", code: "LC", emoji: "🇱🇨", currency: "East Caribbean dollar", currency_code: "XCD" },
    { name: "Saint Vincent and the Grenadines", code: "VC", emoji: "🇻🇨", currency: "East Caribbean dollar", currency_code: "XCD" },
    { name: "Samoa", code: "WS", emoji: "🇼🇸", currency: "Samoan tālā", currency_code: "WST" },
    { name: "San Marino", code: "SM", emoji: "🇸🇲", currency: "Euro", currency_code: "EUR" },
    { name: "Sao Tome and Principe", code: "ST", emoji: "🇸🇹", currency: "São Tomé and Príncipe dobra", currency_code: "STN" },
    { name: "Saudi Arabia", code: "SA", emoji: "🇸🇦", currency: "Saudi riyal", currency_code: "SAR" },
    { name: "Senegal", code: "SN", emoji: "🇸🇳", currency: "West African CFA franc", currency_code: "XOF" },
    { name: "Serbia", code: "RS", emoji: "🇷🇸", currency: "Serbian dinar", currency_code: "RSD" },
    { name: "Seychelles", code: "SC", emoji: "🇸🇨", currency: "Seychellois rupee", currency_code: "SCR" },
    { name: "Sierra Leone", code: "SL", emoji: "🇸🇱", currency: "Sierra Leonean leone", currency_code: "SLE" },
    { name: "Singapore", code: "SG", emoji: "🇸🇬", currency: "Singapore dollar", currency_code: "SGD" },
    { name: "Slovakia", code: "SK", emoji: "🇸🇰", currency: "Euro", currency_code: "EUR" },
    { name: "Slovenia", code: "SI", emoji: "🇸🇮", currency: "Euro", currency_code: "EUR" },
    { name: "Solomon Islands", code: "SB", emoji: "🇸🇧", currency: "Solomon Islands dollar", currency_code: "SBD" },
    { name: "Somalia", code: "SO", emoji: "🇸🇴", currency: "Somali shilling", currency_code: "SOS" },
    { name: "South Africa", code: "ZA", emoji: "🇿🇦", currency: "South African rand", currency_code: "ZAR" },
    { name: "South Korea", code: "KR", emoji: "🇰🇷", currency: "South Korean won", currency_code: "KRW" },
    { name: "Spain", code: "ES", emoji: "🇪🇸", currency: "Euro", currency_code: "EUR" },
    { name: "Sri Lanka", code: "LK", emoji: "🇱🇰", currency: "Sri Lankan rupee", currency_code: "LKR" },
    { name: "Sudan", code: "SD", emoji: "🇸🇩", currency: "Sudanese pound", currency_code: "SDG" },
    { name: "Suriname", code: "SR", emoji: "🇸🇷", currency: "Surinamese dollar", currency_code: "SRD" },
    { name: "Swaziland", code: "SZ", emoji: "🇸🇿", currency: "Swazi lilangeni", currency_code: "SZL" },
    { name: "Sweden", code: "SE", emoji: "🇸🇪", currency: "Swedish krona", currency_code: "SEK" },
    { name: "Switzerland", code: "CH", emoji: "🇨🇭", currency: "Swiss franc", currency_code: "CHF" },
    { name: "Syria", code: "SY", emoji: "🇸🇾", currency: "Syrian pound", currency_code: "SYP" },
    { name: "Taiwan", code: "TW", emoji: "🇹🇼", currency: "New Taiwan dollar", currency_code: "TWD" },
    { name: "Tajikistan", code: "TJ", emoji: "🇹🇯", currency: "Tajikistani somoni", currency_code: "TJS" },
    { name: "Tanzania", code: "TZ", emoji: "🇹🇿", currency: "Tanzanian shilling", currency_code: "TZS" },
    { name: "Thailand", code: "TH", emoji: "🇹🇭", currency: "Thai baht", currency_code: "THB" },
    { name: "Togo", code: "TG", emoji: "🇹🇬", currency: "West African CFA franc", currency_code: "XOF" },
    { name: "Tonga", code: "TO", emoji: "🇹🇴", currency: "Tongan paʻanga", currency_code: "TOP" },
    { name: "Trinidad and Tobago", code: "TT", emoji: "🇹🇹", currency: "Trinidad and Tobago dollar", currency_code: "TTD" },
    { name: "Tunisia", code: "TN", emoji: "🇹🇳", currency: "Tunisian dinar", currency_code: "TND" },
    { name: "Turkey", code: "TR", emoji: "🇹🇷", currency: "Turkish lira", currency_code: "TRY" },
    { name: "Turkmenistan", code: "TM", emoji: "🇹🇲", currency: "Turkmenistan manat", currency_code: "TMT" },
    { name: "Tuvalu", code: "TV", emoji: "🇹🇻", currency: "Australian dollar", currency_code: "AUD" },
    { name: "Uganda", code: "UG", emoji: "🇺🇬", currency: "Ugandan shilling", currency_code: "UGX" },
    { name: "Ukraine", code: "UA", emoji: "🇺🇦", currency: "Ukrainian hryvnia", currency_code: "UAH" },
    { name: "United Arab Emirates", code: "AE", emoji: "🇦🇪", currency: "United Arab Emirates dirham", currency_code: "AED" },
    { name: "United Kingdom", code: "GB", emoji: "🇬🇧", currency: "Pound sterling", currency_code: "GBP" },
    { name: "United States", code: "US", emoji: "🇺🇸", currency: "United States dollar", currency_code: "USD" },
    { name: "Uruguay", code: "UY", emoji: "🇺🇾", currency: "Uruguayan peso", currency_code: "UYU" },
    { name: "Uzbekistan", code: "UZ", emoji: "🇺🇿", currency: "Uzbekistani soʻm", currency_code: "UZS" },
    { name: "Vanuatu", code: "VU", emoji: "🇻🇺", currency: "Vanuatu vatu", currency_code: "VUV" },
    { name: "Vatican City", code: "VA", emoji: "🇻🇦", currency: "Euro", currency_code: "EUR" },
    { name: "Venezuela", code: "VE", emoji: "🇻🇪", currency: "Venezuelan bolívar", currency_code: "VES" },
    { name: "Vietnam", code: "VN", emoji: "🇻🇳", currency: "Vietnamese đồng", currency_code: "VND" },
    { name: "Yemen", code: "YE", emoji: "🇾🇪", currency: "Yemeni rial", currency_code: "YER" },
    { name: "Zambia", code: "ZM", emoji: "🇿🇲", currency: "Zambian kwacha", currency_code: "ZMW" },
    { name: "Zimbabwe", code: "ZW", emoji: "🇿🇼", currency: "United States dollar", currency_code: "USD" }
];
