/*
 USERS:
 create an admin user before any other users:

 - email: response.write@gmail.com
 - password: pa55word!
 - fullname: Bruce Thomas
 - is_admin: true
*/

Table users {
  id integer [primary key]
  email varchar [unique, not null]
  password_hash varchar [not null]
  
  is_global_active boolean [default: true]
  is_admin boolean [default: false]
  
  date_last_seen timestamp
  date_created timestamp [default: `now()` ]
}

/*
USER_PROFILES:
Create a user_profile for the admin user (response.write@gmail.com)

- handle: bruce-thomas
- fullname: Bruce Thomas
- flag_emoji: 🇿🇦
*/

Table user_profiles {
  id integer [primary key]
  user_id integer [not null]

  handle varchar [not null] // eg /u/bruce-thomas
  fullname varchar [not null]
  description text [default: '']
  interest_tags json [not null, default: '[]'] // String[] of interest tags eg. ["drawing", "painting", "sculpture"]

  flag_emoji varchar [not null, default: '🏳️'] // the users country origin

  // Affiliated links (e.g. Gumroad, Etsy) the storefront which will be scraped for product URLs
  // Gumroad: https://azlifemodel.gumroad.com/
  // Etsy: https://www.etsy.com/shop/BorodulyaArt

  affiliate_urls json [default: '[]'] // String[] of affiliate URLs eg. ["https://handle.gumroad.com".com/"]

  date_created timestamp [default: `now()` ]
  is_profile_active boolean [default: true]
}

/*
VENUES:
Use the JSON file '/docs/venues.json' for the most complete curated record set.
the first row is the admin user's venue ("name": "Homerton Library")

The records should correlate to the database.json by matching on postcode, address, or comments
*/

Table venues {
  id integer [primary key, increment]
  name varchar(255) [not null] // eg. "Homerton Library"

  address_line_1 varchar(255) [not null] // eg. "123 Main St"
  address_line_2 varchar(255) [default: ''] // eg. "Suite 456"
  city varchar(100) [not null, default: 'London'] // eg. "London"
  county varchar(100) [default: ''] // eg. "London"
  postcode varchar(20) [not null, default: 'UNKNOWN'] // eg. postcode/zip "SW1A 1AA"
  area varchar(100) [default: ''] // eg. "Camden"
  
  active boolean [not null, default: true]
  
  tz varchar(50) [not null, default: 'europe/london'] // eg. "europe/london"
  
  latitude decimal(10,8)
  longitude decimal(11,8)
  
  capacity integer [not null, default: 0] // max number of attendees

  created_on timestamp [not null, default: `now()`]
  modified_on timestamp [not null, default: `now()`]
  
  is_private boolean [default: false] // private venues or home addresses to be hidden from the website eg. Ciche and compliments (David Burchan)

  venue_tags json [not null, default: '[]'] // eg. ["parking", "step-free", "wheelchair"]
  comments text [default: ''] // eg. Use the entrance on Gravel Road, dial 101 on the innercom and take elevator to 1st floor
}

Enum status_enum {  
  cancelled
  closed
  confirmed
  noshow
  opencall
  pending
}

/*
  CALENDAR:
  Currently all these rows are owned by the admin user (response.write@gmail.com)
  ensure that the event_id is related to a single events.id (of the admin user)
  The calendar is a register of sessions occring on a day in a venue with a model with a host.
  A calendar row without a model_id is presumed CLOSED.

  Any database.json records where 'fullname' value is empty, should be ignored

  Default values for unmatched model_id:
  - model_id: NULL
  - status: 'closed'

  Any model with (TBC) in the fullname:
  - model_id: (match fullname without (TBC))
  - status: 'opencall'

  Any model with 'closed' in the fullname:
  - model_id: NULL
  - status: 'closed'

*/

Table calendar {
  id integer [primary key]
  event_id integer
  model_id integer

  status status_enum

  attendance_inperson integer [default: 0]
  attendance_online integer [default: 0]

  date_time datetime // yyyymmdd hh:mm:ss
  duration decimal [ not null, default: 2.0 ] // hours 2.5

  pose_format text // session's pose format (inherit from event) eg. 5x90sec, 2x5min, 3x10min, break, 2x25min
}

Table models {
  id integer [primary key]

  user_profile_id integer
  phone_number varchar [not null, default: ''] // eg. "07594616416" or "+44 7594 616 416"
  display_name varchar // known as Palendromic
  description text [not null, default: '']

  currency_code char(3) [not null, default: 'GBP'] // USD, GBP, EUR  
  rate_min_hour decimal [default: 20.0]
  rate_min_day decimal [default: 120.0]
  
  tz varchar(50) [not null, default: 'europe/london'] // eg. "europe/london"
  
  work_inperson boolean [default: true]
  work_online boolean [default: false]
  work_photography boolean [default: false]

  work_seeks json [not null, default: '["nude", "portrait", "clothed", "underwear", "costume"]'] // String[]: nude, partial, fashion, costume, bodypaint ...

  social_urls json [default: '[]'] // String[] of social URLs eg. ["https://instagram.com/handle", "https://twitter.com/handle", "https://tiktok.com/handle"]
  
  product_urls json [default: '[]'] // String[] of product URLs eg. ["https://handle.etsy.com", "https://handle.gumroad.com"]
  date_birthday timestamp // legal age 20
  date_experience timestamp // years of experience

  sex tinyint [not null, default: 0] // 0 none, 1 male, 2 female
  pronouns varchar [not null, default: ''] // he/him she/her they/them
}

/*
  HOSTS:
  Create a host row for the admin user (response.write@gmail.com)
  that matched the user_profile_id of the admin user

  All calendar rows should reference this host

  name: Life Drawing Art
  phone_number: 07594616416
  social_urls: ['https://instagram.com/lifedrawing.art','https://lifedrawing.art']

  - Create any missing users and user_profiles for the other hosts 
  - use placeholder data for the missing fields
  - each host should have a unique handle and match one or more events
*/

Table hosts {
  id integer [primary key]
  user_profile_id integer [not null]

  name varchar [not null]
  description text
  phone_number varchar

  social_urls json [default: '[]'] // String[] of social URLs eg. ["https://instagram.com/handle", "https://twitter.com/handle", "https://tiktok.com/handle"]

  currency_code char(3)  [not null, default: 'GBP'] // USD, GBP, EUR
  
  rate_max_hour decimal [not null, default: 25.00] // per hour
  rate_max_day decimal [not null, default: 150.00] // six hours

  tz varchar(50) [not null, default: 'europe/london'] // eg. "europe/london"

  date_created timestamp [not null, default: `now()`]
  host_tags json [not null, default: '[]'] // from database.json venues "tag" eg. ["heating", "materials", "lights", "snacks"]
}

Enum frequency_enum {
  adhoc
  once
  daily
  weekly
  biweekly
  triweekly
  monthly
  quarterly
  annually
}

Enum week_day_enum {
  sunday
  monday
  tuesday
  wednesday
  thursday
  friday
  saturday
  unknown
}

Table events {
  id integer [primary key]
  venue_id integer [null] // nullable for online events
  host_user_id integer [not null]
  name varchar [not null] //eg. "Drawing in the Library"
  description varchar // eg. "Join us for the weekly session in the Homerton Library"
  images json [not null, default: '[]'] // String[] eg. ["https://domain.com/image.jpg"]

  frequency frequency_enum [not null, default: 'weekly']
  week_day week_day_enum [not null, default: 'unknown']

  pricing_table json [not null, default: '[]'] // String[]: [ticket-name,ticket-price] eg. ["General Admission", 10.00, "Student", 5.00]
  pricing_text text [not null, default: ''] // plain-text (no HTML) eg. "Bring your own and get a 10% discount, bring a friend and get a 20% discount"
  pricing_tags json [not null, default: '[]'] // eg. String[]: eg. ["loyalty", "cash", "card", "paypal"]

  pose_format text [not null, default: 'Mixed poses: gesture, short, medium, long'] // general pose format, for an event, inherited by the calendar session
}

Table exchange_rates {
  currency_code char(3) [primary key]
  rate_to_usd decimal(10,6) [not null]
  updated_at timestamptz [not null, default: `now()`]
}

Table tracking {
  id integer [primary key]
  user_id integer [not null]
  href varchar [not null]
  timestamp timestamptz
}

Ref: "calendar"."event_id" < "events"."id"
Ref: "calendar"."model_id" < "models"."id"

Ref: "events"."host_user_id" < "hosts"."user_profile_id"

Ref: "hosts"."currency_code" < "exchange_rates"."currency_code"
Ref: "hosts"."user_profile_id" < "user_profiles"."id"

Ref: "models"."currency_code" < "exchange_rates"."currency_code"
Ref: "models"."user_profile_id" < "user_profiles"."id"

Ref: "user_profiles"."user_id" < "users"."id"

Ref: "users"."id" < "tracking"."user_id"

Ref: "venues"."id" < "events"."venue_id"
